[build]
command = "swift package --allow-writing-to-directory .docs generate-documentation --disable-indexing --transform-for-static-hosting --output-path .docs"
publish = ".docs"


[[redirects]]
from = "/"
to = "/documentation/swiftwombat/"
status = 302
force = true
